### ISSUE TITLE
Can this firmware update work without anything on RB6?

### ISSUE THREAD

**Issue by Hrvojeee** [tobiaswaldvogel/livolo-thermostat#1]
Hi Tobias,

First off, amazing work with the thermostat, you are really a pro!!

I was also attracted by the nice visual appearance of the thermostat but after a while i realized the functionality is really poor and now my really expensive heating pump system is not working perfectly because of the lousy thermostat. And like you mentioned, i have the whole house full of light switches, wall outlets and thermostats from Livolo, so i either change everything or nothing.. But then you came to the rescue:)

Now for the question.. I did a different hw change than you but i updated the firmware with your hex file. What i did is just extract the RB4 thermostat outside the box (added some wires through the existing small holes and reconnected it from the outside), but i did not touch the RB6 internal thermostat (did not want to replace it with the light sensor as i like the thermostat shinning in the dark). But after the changes it is still reading wrong temperature (4-5 celsius higher than actual room temperature). So, i am assuming that its because the firmware is still reading the temperature from the RB6 sensor which i did not touch. Is that correct?
If yes, what would happen if i would just get rid of the existing RB6 temperature sensor without adding the light sensor? Would everything work and would the thermostat start reading temperature from the extracted RB4 sensor (hopefully it would be able to get better reading in that case)? Would i have to change the software also in that case? I tried reading your firmware with MPLab IDE but i’m not that good with low level code (and this is my first project with soldering and microcontrollers) and don’t think i could program it myself, so i can’t figure out what would happen if i just get rid of the internal temperature sensor?

Thanks a lot in advance for your time, wonderful project you did!! Hope the Livolo guys see this as their original software is really bad..

**Comment by tobiaswaldvogel** [comment]
Hi Hrvojeee

Great to hear that you managed you get this firmware on your thermosthat. I'm glad that it is useful for others as well.
It's true that assembly langauge is not that easy to read.  But I did a lot off assembly programming when I was child, so I have quite some experience with that. Nevertheless it took me also some time to do the reverse engeneering of the board. as you can't read out their software (copy protected). At the end it is completely from scratch, but it was a nice challenge.

Well, the initialization logic works pretty much as follows:

- Check if thermometer present on RB4 => If yes then use it
- Else check for thermometer on RB6. If present use it and aussume that there is a light sensor on RB4
- If there is no thermometer on RB6 indicate failure (Display 03 with C and F blinking once per second)

So actually there is no need to remove the thermomether on RB6, but it would also not do any harm.

Coming back to your actual problem: I'm sure that your reading is coming from RB4, but you can also remove RB6 to proof it.

In my thermostats I also had to put an offset because it seems that the temperature at the wall is most of the time a little bit higher than in the middle of the room. There are also a lot of things which might affect the measurement. Even now that you moved it outside, the temperature from the inside might affect a little bit. The temperature is actually measured at the ground pin and the cables are conducting the heat as well. This is why I came up with the idea to use the SMD version on a copper plate. But I have to admit that it took me quite a while to built that.

If you have a stable reading then easiest way would be, just to measure the temperature at the desired place, and then adjust the offset on the thermostat. In my case it was also usually 2 degrees difference.

The original software is really totally useless. My valves usually take 2-3 minutes to open, so I use even a longer delay before acting on a temperature change.

I wouldn't mind if the Levolo guys would just adapt but it seems they are not interested to improve it. Really a pity because all the rest, the sockets and the switches a very nice.

**Comment by Hrvojeee** [comment]
Thanks Tobias for the quick reply..

Ok so i am probably getting the reading from RB4 then but its also not accurate which is too bad.. Then i might get the sensor back into the housing since the measurement is more or less the same (wrong) and as you suggested i can play around with the offset..

Yes in my case also the thermostat would send the electrical signal to the valve too many times in a short amount of time which for sure doesn’t do any good to the heating system.. So that + the wrong temperature reading was the reason i started googling for new firmware and found your project.. 

Thanks again for the project you shared and your reply.. will close this now..
